------------------------------------------------------------------
-- RELEASE & PROMO ORCHESTRATOR
-- SCHEMA QUALIFIER: Z73460
--
-- RUN ORDER:
--   1. EXT_EVENT_T   (NO FK DEPENDENCIES)
--   2. RELEASE_T     (NO FK DEPENDENCIES)
--   3. PROMO_T       (FK -> RELEASE_T)
--   4. CLASH_SCORE_T (FK -> RELEASE_T X2)
--
-- RUN VIA SPUFI OR INCLUDE IN DBSCHEMA.JCL USING DSNTEP2.
------------------------------------------------------------------

------------------------------------------------------------------
-- TABLE 1: EXT_EVENT_T
-- EXTERNAL EVENTS THAT INFLUENCE CLASH RISK SCORING.
------------------------------------------------------------------
CREATE TABLE Z73460.EXT_EVENT_T
  (EVENT_ID      CHAR(10)     NOT NULL,
   EVENT_NAME    VARCHAR(100) NOT NULL,
   EVENT_DATE    DATE         NOT NULL,
   EVENT_END     DATE,
   IMPACT_GENRE  CHAR(20)     NOT NULL,
   IMPACT_MARKET CHAR(20)     NOT NULL,
   SEVERITY      CHAR(10)     NOT NULL,
   CONSTRAINT PK_EVENT
     PRIMARY KEY (EVENT_ID),
   CONSTRAINT CK_EVT_SEVERITY
     CHECK (SEVERITY IN ('LOW','MEDIUM','HIGH')),
   CONSTRAINT CK_EVT_WINDOW
     CHECK (EVENT_END IS NULL OR EVENT_END >= EVENT_DATE),
   CONSTRAINT CK_EVT_GENRE
     CHECK (IMPACT_GENRE IN
      ('DRAMA','COMEDY','SPORT','DOCUMENTARY','THRILLER','OTHER',
        'GLOBAL')),
   CONSTRAINT CK_EVT_MARKET
     CHECK (IMPACT_MARKET IN ('US','EU','APAC','LATAM','GLOBAL'))
  )
  IN DATABASE Z73460;

CREATE INDEX Z73460.IX_EVT_DATE
  ON Z73460.EXT_EVENT_T (EVENT_DATE ASC, EVENT_END ASC);

CREATE INDEX Z73460.IX_EVT_MARKET_GENRE
  ON Z73460.EXT_EVENT_T (IMPACT_MARKET ASC, IMPACT_GENRE ASC);

------------------------------------------------------------------
-- TABLE 2: RELEASE_T
-- MASTER RELEASE CALENDAR. CENTRAL TABLE REFERENCED BY ALL OTHERS.
------------------------------------------------------------------
CREATE TABLE Z73460.RELEASE_T
  (RELEASE_ID    CHAR(10)     NOT NULL,
   TITLE         VARCHAR(100) NOT NULL,
   GENRE         CHAR(20)     NOT NULL,
   PLATFORM      CHAR(20)     NOT NULL,
   RELEASE_DATE  DATE         NOT NULL,
   WINDOW_END    DATE         NOT NULL,
   TARGET_MARKET CHAR(20)     NOT NULL,
   STATUS        CHAR(10)     NOT NULL WITH DEFAULT 'DRAFT',
   ADDED_TS      TIMESTAMP    NOT NULL,
   UPDATED_TS    TIMESTAMP    NOT NULL,
   CONSTRAINT PK_RELEASE
     PRIMARY KEY (RELEASE_ID),
   CONSTRAINT CK_REL_GENRE
     CHECK (GENRE IN
       ('DRAMA','COMEDY','SPORT','DOCUMENTARY','THRILLER','OTHER')),
   CONSTRAINT CK_REL_PLATFORM
     CHECK (PLATFORM IN ('STREAMING','LINEAR','THEATRICAL')),
   CONSTRAINT CK_REL_MARKET
     CHECK (TARGET_MARKET IN ('US','EU','APAC','LATAM','GLOBAL')),
   CONSTRAINT CK_REL_STATUS
     CHECK (STATUS IN ('DRAFT','CONFIRMED','RELEASED','CANCELLED')),
   CONSTRAINT CK_REL_WINDOW
     CHECK (WINDOW_END >= RELEASE_DATE)
  )
  IN DATABASE Z73460;

CREATE INDEX Z73460.IX_REL_DATE
  ON Z73460.RELEASE_T (RELEASE_DATE ASC, WINDOW_END ASC);

CREATE INDEX Z73460.IX_REL_STATUS
  ON Z73460.RELEASE_T (STATUS ASC);

CREATE INDEX Z73460.IX_REL_MARKET_GENRE
  ON Z73460.RELEASE_T (TARGET_MARKET ASC, GENRE ASC);

------------------------------------------------------------------
-- TABLE 3: PROMO_T
-- PROMOTIONAL CHECKLIST ITEMS. ONE RELEASE HAS MANY PROMO ITEMS.
------------------------------------------------------------------
CREATE TABLE Z73460.PROMO_T
  (PROMO_ID    CHAR(10)    NOT NULL,
   RELEASE_ID  CHAR(10)    NOT NULL,
   ITEM_NAME   VARCHAR(80) NOT NULL,
   STATUS      CHAR(10)    NOT NULL WITH DEFAULT 'PENDING',
   DUE_DATE    DATE,
   OWNER       VARCHAR(50),
   UPDATED_TS  TIMESTAMP   NOT NULL,
   CONSTRAINT PK_PROMO
     PRIMARY KEY (PROMO_ID),
   CONSTRAINT FK_PROMO_RELEASE
     FOREIGN KEY (RELEASE_ID)
     REFERENCES Z73460.RELEASE_T (RELEASE_ID),
   CONSTRAINT CK_PRO_STATUS
     CHECK (STATUS IN ('PENDING','IN-PROG','DONE'))
  )
  IN DATABASE Z73460;

CREATE INDEX Z73460.IX_PRO_RELEASE
  ON Z73460.PROMO_T (RELEASE_ID ASC, STATUS ASC);

------------------------------------------------------------------
-- TABLE 4: CLASH_SCORE_T
-- PAIRWISE CLASH RISK SCORES. WRITTEN ONLY BY BATCH JOB CLSHBAT.
-- CLASHRDR CICS PROGRAM READS THIS TABLE (NEVER WRITES).
------------------------------------------------------------------
CREATE TABLE Z73460.CLASH_SCORE_T
  (SCORE_ID      CHAR(10)      NOT NULL,
   RELEASE_ID    CHAR(10)      NOT NULL,
   CLASH_WITH_ID CHAR(10)      NOT NULL,
   RISK_SCORE    DECIMAL(5,2)  NOT NULL,
   SCORE_FACTORS VARCHAR(200),
   SCORED_TS     TIMESTAMP     NOT NULL,
   CONSTRAINT PK_SCORE
     PRIMARY KEY (SCORE_ID),
   CONSTRAINT FK_SCR_RELEASE
     FOREIGN KEY (RELEASE_ID)
     REFERENCES Z73460.RELEASE_T (RELEASE_ID),
   CONSTRAINT FK_SCR_CLASH_WITH
     FOREIGN KEY (CLASH_WITH_ID)
     REFERENCES Z73460.RELEASE_T (RELEASE_ID),
   CONSTRAINT CK_SCR_SCORE
     CHECK (RISK_SCORE BETWEEN 0.00 AND 100.00),
   CONSTRAINT CK_SCR_NOSELF
     CHECK (RELEASE_ID <> CLASH_WITH_ID)
  )
  IN DATABASE Z73460;

CREATE INDEX Z73460.IX_SCR_RELEASE
  ON Z73460.CLASH_SCORE_T (RELEASE_ID ASC, RISK_SCORE DESC);

CREATE INDEX Z73460.IX_SCR_SCORED_TS
  ON Z73460.CLASH_SCORE_T (SCORED_TS ASC);

------------------------------------------------------------------
-- TABLE 5: CHANGE_LOG
-- AUDIT TRAIL FOR ADD/UPD/DEL OPERATIONS ACROSS RELEASE_T, PROMO_T,
-- EXT_EVENT_T. WRITTEN BY RELSMGR/PROMGR/EVTMGR (BEST-EFFORT,
-- NOT PART OF THE MAIN TRANSACTION'S SUCCESS/FAILURE PATH).
-- CLASH_SCORE_T IS READ-ONLY (WRITTEN BY BATCH CLSHBAT), NOT LOGGED.
--
-- NOTE: LOG_ID USES THE SAME SEQ_* PATTERN AS EVERY OTHER TABLE
-- (SEQ_LOG, DEFINED BELOW) INSTEAD OF GENERATED ALWAYS AS IDENTITY,
-- FOR CONSISTENCY WITH RELEASE_T/PROMO_T/CLASH_SCORE_T'S PK
-- GENERATION APPROACH. COBOL DOES
--   SELECT NEXT VALUE FOR Z73460.SEQ_LOG INTO :HV-LOG-ID
-- THEN EXPLICITLY INCLUDES HV-LOG-ID IN THE INSERT COLUMN LIST.
------------------------------------------------------------------
CREATE TABLE Z73460.CHANGE_LOG
  (LOG_ID       INTEGER      NOT NULL,
   ENTITY_TYPE  CHAR(10)     NOT NULL,
   ENTITY_ID    CHAR(10)     NOT NULL,
   ACTION       CHAR(6)      NOT NULL,
   DETAILS      VARCHAR(200),
   CHANGED_BY   CHAR(10)     NOT NULL WITH DEFAULT 'Z73460',
   CHANGED_TS   TIMESTAMP    NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
   CONSTRAINT PK_CHANGE_LOG
     PRIMARY KEY (LOG_ID),
   CONSTRAINT CK_LOG_ENTITY_TYPE
     CHECK (ENTITY_TYPE IN ('RELEASE','PROMO','EVENT')),
   CONSTRAINT CK_LOG_ACTION
     CHECK (ACTION IN ('ADD','UPD','DEL'))
  )
  IN DATABASE Z73460;

CREATE INDEX Z73460.IX_LOG_ENTITY
  ON Z73460.CHANGE_LOG (ENTITY_TYPE ASC, ENTITY_ID ASC);

CREATE INDEX Z73460.IX_LOG_TS
  ON Z73460.CHANGE_LOG (CHANGED_TS DESC);

------------------------------------------------------------------
-- DB2 SEQUENCES - USED BY COBOL PROGRAMS TO GENERATE PKS FOR
-- EVERY TABLE, INCLUDING CHANGE_LOG. DEFINED HERE SO PHASE 1
-- SMOKE TESTS CAN REFERENCE THEM.
--
-- USAGE IN COBOL:
--   EXEC SQL
--     SELECT NEXT VALUE FOR Z73460.SEQ_RELEASE
--     INTO :HV-NEXT-SEQ
--   END-EXEC
--   THEN FORMAT: 'REL' || TRIM(HV-NEXT-SEQ)  -- e.g. REL1, REL24
--
-- SEQ_RELEASE RUNS WITH NO CACHE - CACHED SEQUENCES WERE FOUND TO
-- RETURN STALE VALUES ACROSS DIFFERENT DB2 THREADS UNDER CICS, SO
-- RELEASE_T'S SEQUENCE TRADES A LITTLE THROUGHPUT FOR CORRECTNESS.
-- THE OTHER SEQUENCES KEEP THE DEFAULT CACHE SINCE THAT ISSUE
-- WAS ONLY OBSERVED ON SEQ_RELEASE IN PRACTICE.
------------------------------------------------------------------
CREATE SEQUENCE Z73460.SEQ_RELEASE
  START WITH 1 INCREMENT BY 1 NO MAXVALUE NO CYCLE NO CACHE;

CREATE SEQUENCE Z73460.SEQ_PROMO
  START WITH 1 INCREMENT BY 1 NO MAXVALUE NO CYCLE CACHE 20;

CREATE SEQUENCE Z73460.SEQ_SCORE
  START WITH 1 INCREMENT BY 1 NO MAXVALUE NO CYCLE CACHE 20;

CREATE SEQUENCE Z73460.SEQ_EVENT
  START WITH 1 INCREMENT BY 1 NO MAXVALUE NO CYCLE CACHE 20;

CREATE SEQUENCE Z73460.SEQ_LOG
  START WITH 1 INCREMENT BY 1 NO MAXVALUE NO CYCLE CACHE 20;
------------------------------------------------------------------
-- END OF DDL
------------------------------------------------------------------
