CREATE TABLE Z73460.CHANGE_LOG
  (LOG_ID       INTEGER      NOT NULL,
   ENTITY_TYPE  CHAR(10)     NOT NULL,
   ENTITY_ID    CHAR(10)     NOT NULL,
   ACTION       CHAR(6)      NOT NULL,
   DETAILS      VARCHAR(200),
   CHANGED_BY   CHAR(10)     NOT NULL WITH DEFAULT 'Z73460',
   CHANGED_TS   TIMESTAMP    NOT NULL,
   CONSTRAINT PK_CHANGE_LOG
     PRIMARY KEY (LOG_ID),
   CONSTRAINT CK_LOG_ENTITY_TYPE
     CHECK (ENTITY_TYPE IN ('RELEASE','PROMO','EVENT')),
   CONSTRAINT CK_LOG_ACTION
     CHECK (ACTION IN ('ADD','UPD','DEL'))
  )
  IN DATABASE Z73460;
 
CREATE INDEX Z73460.IX_LOG_ENTITY
  ON Z73460.CHANGE_LOG (ENTITY_TYPE ASC, ENTITY_ID ASC);
 
CREATE INDEX Z73460.IX_LOG_TS
  ON Z73460.CHANGE_LOG (CHANGED_TS DESC);
 
CREATE SEQUENCE Z73460.SEQ_LOG
  START WITH 1 INCREMENT BY 1 NO MAXVALUE NO CYCLE CACHE 20;
 
