------------------------------------------------------------------
-- RELEASE & PROMO ORCHESTRATOR   DB2 SEED DATA
-- SCHEMA QUALIFIER: Z73460
--
-- RUN AFTER CREATE TABLES HAS BEEN EXECUTED SUCCESSFULLY.
-- RUN VIA SPUFI OR INCLUDE IN DBSCHEMA.JCL AFTER THE DDL STEP.
--
-- INSERT ORDER MUST FOLLOW FK DEPENDENCY:
--   1. EXT_EVENT_T  (NO FK DEPS)
--   2. RELEASE_T    (NO FK DEPS)
--   3. PROMO_T      (FK -> RELEASE_T)
--   CLASH_SCORE_T INTENTIONALLY LEFT EMPTY   CLSHBAT POPULATES IT.
------------------------------------------------------------------

------------------------------------------------------------------
-- EXT_EVENT_T SEED ROWS
-- THESE EVENTS ARE USED BY CLSHBAT TO SCORE EVENT PROXIMITY.
------------------------------------------------------------------
INSERT INTO Z73460.EXT_EVENT_T
  (EVENT_ID, EVENT_NAME, EVENT_DATE, EVENT_END,
   IMPACT_GENRE, IMPACT_MARKET, SEVERITY)
VALUES
  ('EVT1', 'FIFA WORLD CUP FINAL',
   '2025-11-15', '2025-11-15', 'SPORT', 'GLOBAL', 'HIGH');

INSERT INTO Z73460.EXT_EVENT_T
  (EVENT_ID, EVENT_NAME, EVENT_DATE, EVENT_END,
   IMPACT_GENRE, IMPACT_MARKET, SEVERITY)
VALUES
  ('EVT2', 'US THANKSGIVING WEEKEND',
   '2025-11-27', '2025-11-30', 'GLOBAL', 'US', 'MEDIUM');

INSERT INTO Z73460.EXT_EVENT_T
  (EVENT_ID, EVENT_NAME, EVENT_DATE, EVENT_END,
   IMPACT_GENRE, IMPACT_MARKET, SEVERITY)
VALUES
  ('EVT3', 'EU SUMMER HOLIDAY PEAK',
   '2025-08-01', '2025-08-31', 'GLOBAL', 'EU', 'LOW');

INSERT INTO Z73460.EXT_EVENT_T
  (EVENT_ID, EVENT_NAME, EVENT_DATE, EVENT_END,
   IMPACT_GENRE, IMPACT_MARKET, SEVERITY)
VALUES
  ('EVT4', 'US LABOR DAY WEEKEND',
   '2025-08-30', '2025-09-01', 'GLOBAL', 'US', 'MEDIUM');

------------------------------------------------------------------
-- RELEASE_T SEED ROWS
-- MIX OF CONFIRMED (BATCH WILL SCORE THESE) AND ONE DRAFT (IGNORED).
------------------------------------------------------------------
INSERT INTO Z73460.RELEASE_T
  (RELEASE_ID, TITLE, GENRE, PLATFORM,
   RELEASE_DATE, WINDOW_END, TARGET_MARKET, STATUS,
   ADDED_TS, UPDATED_TS)
VALUES
  ('REL1', 'THE LAST SIGNAL', 'DRAMA', 'STREAMING',
   '2025-09-05', '2025-10-05', 'US', 'CONFIRMED',
   CURRENT TIMESTAMP, CURRENT TIMESTAMP);

INSERT INTO Z73460.RELEASE_T
  (RELEASE_ID, TITLE, GENRE, PLATFORM,
   RELEASE_DATE, WINDOW_END, TARGET_MARKET, STATUS,
   ADDED_TS, UPDATED_TS)
VALUES
  ('REL2', 'NIGHT PROTOCOL', 'THRILLER', 'STREAMING',
   '2025-09-12', '2025-10-12', 'US', 'CONFIRMED',
   CURRENT TIMESTAMP, CURRENT TIMESTAMP);

INSERT INTO Z73460.RELEASE_T
  (RELEASE_ID, TITLE, GENRE, PLATFORM,
   RELEASE_DATE, WINDOW_END, TARGET_MARKET, STATUS,
   ADDED_TS, UPDATED_TS)
VALUES
  ('REL3', 'WORLD CUP COUNTDOWN', 'SPORT', 'LINEAR',
     '2025-11-01', '2025-11-30', 'GLOBAL', 'CONFIRMED',
   CURRENT TIMESTAMP, CURRENT TIMESTAMP);

INSERT INTO Z73460.RELEASE_T
  (RELEASE_ID, TITLE, GENRE, PLATFORM,
   RELEASE_DATE, WINDOW_END, TARGET_MARKET, STATUS,
   ADDED_TS, UPDATED_TS)
VALUES
  ('REL4', 'COMEDY CLUB S2', 'COMEDY', 'STREAMING',
   '2025-09-20', '2025-10-20', 'EU', 'CONFIRMED',
   CURRENT TIMESTAMP, CURRENT TIMESTAMP);

INSERT INTO Z73460.RELEASE_T
  (RELEASE_ID, TITLE, GENRE, PLATFORM,
   RELEASE_DATE, WINDOW_END, TARGET_MARKET, STATUS,
   ADDED_TS, UPDATED_TS)
VALUES
  ('REL5', 'DRAFT TITLE X', 'DRAMA', 'STREAMING',
   '2025-12-01', '2025-12-31', 'US', 'DRAFT',
   CURRENT TIMESTAMP, CURRENT TIMESTAMP);

------------------------------------------------------------------
-- PROMO_T SEED ROWS
-- THREE ITEMS FOR REL1, ONE EACH FOR REL2 & REL3.
------------------------------------------------------------------
INSERT INTO Z73460.PROMO_T
  (PROMO_ID, RELEASE_ID, ITEM_NAME, STATUS, DUE_DATE, OWNER, UPDATED_TS)
VALUES ('PRO1','REL1','TRAILER UPLOADED',
        'DONE','2025-08-01','PROMO TEAM', CURRENT TIMESTAMP);

INSERT INTO Z73460.PROMO_T
  (PROMO_ID, RELEASE_ID, ITEM_NAME, STATUS, DUE_DATE, OWNER, UPDATED_TS)
VALUES ('PRO2','REL1','PRESS KIT SENT',
        'IN-PROG','2025-08-15','PR TEAM', CURRENT TIMESTAMP);

INSERT INTO Z73460.PROMO_T
  (PROMO_ID, RELEASE_ID, ITEM_NAME, STATUS, DUE_DATE, OWNER, UPDATED_TS)
VALUES ('PRO3','REL1','SOCIAL MEDIA CAMPAIGN',
        'PENDING','2025-08-25','SOCIAL TEAM', CURRENT TIMESTAMP);

INSERT INTO Z73460.PROMO_T
  (PROMO_ID, RELEASE_ID, ITEM_NAME, STATUS, DUE_DATE, OWNER, UPDATED_TS)
VALUES ('PRO4','REL2','TRAILER UPLOADED',
        'PENDING','2025-08-10','PROMO TEAM', CURRENT TIMESTAMP);

INSERT INTO Z73460.PROMO_T
  (PROMO_ID, RELEASE_ID, ITEM_NAME, STATUS, DUE_DATE, OWNER, UPDATED_TS)
VALUES ('PRO5','REL3','BROADCAST SLOT BOOKED',
        'DONE','2025-10-01','SCHEDULING', CURRENT TIMESTAMP);

------------------------------------------------------------------
-- CLASH_SCORE_T   INTENTIONALLY EMPTY AT SEED TIME.
-- THE BATCH JOB CLSHBAT (PHASE 3) WILL POPULATE THIS TABLE.
------------------------------------------------------------------

------------------------------------------------------------------
-- END OF SEED DATA
------------------------------------------------------------------
